### PR TITLE
Added alert box

### PR DESCRIPTION
**Pull request by Zibethin**
- added alert box with latest 5 alerts (linked to google sheet)
- removed a few stray div's

### CODE REVIEW

**Comment by Zibethin** [comment]
Hi, you may notice a few re-indentations... my editor had different default indentation, only realised it after committing.

**Comment by Zibethin** [comment]
This is what the new page looks like (takes a few seconds to fully load): https://htmlpreview.github.io/?https://github.com/Zibethin/homepage/blob/master/index.html

**Comment by Zibethin** [comment]
Also the preview is not perfect so it will have a few errors on the map but the code should work

**Comment by guipizzini** [comment]
Awesome! Before doing the pull; could we have the "titles" of the columns imported as well, please?

**Comment by Zibethin** [comment]
I've added headers to the table :) https://github.com/IFRCGo/homepage/pull/2/commits/baf7bb7d61f28e19f921b49353f908a48c5bc842

**Comment by dalekunce** [comment]
This will need to be made to the ifrcgo_v2 site as well

**Pull request merged**
